### ISSUE TITLE
ESRCH error when killing parallel processes

### ISSUE THREAD

**Issue by RyanZim** [paulpflug/script-runner#1]
I have noticed this issue various places. When I `run-npm -p` and kill the process with `^C`, it throws an ESRCH error.

This happens with different scripts, but one example is running [`imagemin-cli`](https://github.com/imagemin/imagemin-cli). I created a test case gist at https://gist.github.com/RyanZim/34bc12ef8cbd99cb6fd366d498701c14. To reproduce, run `npm test`. The script will `echo` "Press ^C". When it does, press `^C` and it should throw the error. Here is my terminal output for Lubuntu Trusty with bash:

```
$ npm test

> t-sr@1.0.0 test /home/ryan/t-sr
> run-npm -p 'imagemin' 'instruct'

Press ^C
^C
$ internal/process.js:158
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:949:11)
    at process.kill (internal/process.js:158:13)
    at ChildProcess.child.close (/home/ryan/t-sr/node_modules/better-spawn/index.js:51:24)
    at Object.closeAll [as close] (/home/ryan/t-sr/node_modules/script-runner/lib/index.js:61:22)
    at process.<anonymous> (/home/ryan/t-sr/node_modules/script-runner/lib/index.js:145:62)
    at emitNone (events.js:86:13)
    at process.emit (events.js:185:7)
    at Signal.wrap.onsignal (internal/process.js:186:44)
^C
$
```

Hope you can get this untangled. Thanks for the great tool!

**Comment by paulpflug** [comment]
thanks for reporting :+1:

**Comment by RyanZim** [comment]
Thanks for the quick fix!
